### ISSUE TITLE
Move "anything" a "modules/" - structure?

### ISSUE THREAD

**Issue by b3nl** [EllisV/oxid-console#33]
What do you think about moving everything custom into a modules directory?

**Comment by EllisV** [comment]
Hello Björn,

There has been already several people asking this question. A thing is that modules suppose to be activated per shop (think of Enterprise Edition). Should OXID console work if it is activated in subshop but not activated in root shop? It is just against the idea of what OXID means by module. In current implementation OXID console is treated as part of OXID framework and I had a plan to contribute this OXID core itself.

But today I believe OXID has big plans on changing their framework as you can see they are giving a first try on composer integration and stuff like that. Introducing OXID Console in their core package will give them more things to support and more stuff to break their backwards compatibility on after big architectural changes.

I am aware that updating or installing OXID console to your project is kind of more painful than it usually should be and this wouldn't be a problem if it would go as a module. But I do not really want to put it as a module because I do not really see it like that. What do you think?

Also see #25

**Comment by nymo** [comment]
Hi EllisV,
nice extention I like the features. I would aggree to @b3nl in putting everything into a module. Problem is you're mixing custom with core code from oxid. Therefore it's not easy to update to a new oxid version.
In our team we avoid adding any custom code into the core functions/folders of oxid and move everything into an own module. Makes updates easier and you always knew which code was written from who.

Since oxid is going to implement composer the shop will have an separate vendor folder. Maybe this extention could be moved right now into a vendor folder? What do you think?

**Comment by b3nl** [comment]
I am still not sure what to use. This package or https://github.com/marcharding/oxrun/. I agree with @EllisV that this is no real module but the mixing with the core is to heavy for me. 
I like @marcharding approach, even if is not module-centric aswell. I would like the combination of them both. A clean oxid structure and an encapsulated .phar/bin.

**Comment by EllisV** [comment]
@nymo @b3nl I'll give it a go for OXID console to be installed as a composer package. I'll keep you guys posted on #34

**Comment by alfredbez** [comment]
You can install OXID console in one folder and create symlinks to make updates easier.
